
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * 
 * 
 * 
 * @author arant
 */
public class LogIn extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogIn.class.getName());
    
    
    private String requiredEmail = "admin";
    private String requiredPassword = "12345";
    private LogIn login;
    
    public void setCredentials(String email, String password){
        this.requiredEmail = email;
        this.requiredPassword = password;
    }
    
    public void openSignUpForm(){
        SignUp signUp = new SignUp(this);
        signUp.setVisible(true);
    }
    
    public void openDashboard(){
        DashBoard dash = new DashBoard();
        dash.setVisible(true);
        this.setVisible(false);
    }
    

    /**
     * Creates new form logIn
     */
    public LogIn() {
    initComponents();
    
    setResizable(false);
    
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        LogIn_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        SignUp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("and Found!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 165, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sign in your BISU account");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 235, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Your email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 329, -1, -1));

        Email.setBackground(new java.awt.Color(255, 255, 255));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(0, 0, 0));
        Email.setToolTipText("ashborn@gmail.com");
        Email.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), null));
        Email.setMargin(new java.awt.Insets(5, 10, 5, 10));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 355, 676, 45));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Passsword");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 418, -1, -1));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(0, 0, 0));
        Password.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), null));
        Password.setMargin(new java.awt.Insets(5, 10, 5, 10));
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 444, 676, 45));

        jCheckBox1.setBackground(new java.awt.Color(153, 102, 255));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Remember me");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 495, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Forgot Password?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 497, -1, -1));

        LogIn_btn.setBackground(new java.awt.Color(255, 255, 255));
        LogIn_btn.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        LogIn_btn.setForeground(new java.awt.Color(0, 0, 0));
        LogIn_btn.setText("Login");
        LogIn_btn.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.controlShadow, 2, true));
        LogIn_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogIn_btn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                LogIn_btnMouseMoved(evt);
            }
        });
        LogIn_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogIn_btnMouseClicked(evt);
            }
        });
        LogIn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogIn_btnActionPerformed(evt);
            }
        });
        jPanel1.add(LogIn_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 521, 210, 61));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Welcome Back to Lost ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 95, -1, -1));

        SignUp.setBackground(new java.awt.Color(255, 255, 255));
        SignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignUp.setText("Sign-Up");
        SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMouseClicked(evt);
            }
        });
        jPanel1.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 588, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 700));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("jToggleButton1");
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 0, 830, 700));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1222, 6, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bohol Island State University.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseClicked
        // TODO add your handling code here:
        openSignUpForm();
        this.setVisible(false);
    }//GEN-LAST:event_SignUpMouseClicked

    private void LogIn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogIn_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogIn_btnActionPerformed

    private void LogIn_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogIn_btnMouseClicked
        // TODO add your handling code here:
        String email = Email.getText();
        String password = new String(Password.getPassword());

        if(email.isEmpty() && password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Requires complete email and password","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            //get database connection
            Connection connection = DataBaseConnection.getConnection();
            
            if(connection!=null){
                // i prepare ang sql query (using prepared statement to prevent sql injection)
                // the ? are placeholders to avoid sql injection
                // preparedStatement is a safe way to send data sa query
                // akong gi search tas ang query in a database is a request for information or an action to be performed on data within a database
                String query = "SELECT * FROM STUDENT WHERE EMAIL = ? AND PASSWORD = ?";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                
                //inserts actual values sa ?
                preparedStatement.setString(1, email);
                preparedStatement.setString(2, password);
                
                // Execute query
                // This sends the query to MySQL
                // ResultSet = returned rows from the database natods
                ResultSet resultset = preparedStatement.executeQuery();
                
                // check if user exists
                if(resultset.next()){
                    JOptionPane.showMessageDialog(this, 
                            "Log-In Successful\n WElcome",
                            "Success",
                            JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this,
                            "Invalid Username or Password!",
                            "log-in failed",
                            JOptionPane.ERROR_MESSAGE);
                }
                
                // close the resourcesses
                // very important to avoid crashes and good coding hygiene ingon chat gpt
                resultset.close();
                preparedStatement.close();
                connection.close();
            }
        }catch(SQLException exception){
            JOptionPane.showMessageDialog(this,
                    "Database error" + exception.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        openDashboard();
        

    }//GEN-LAST:event_LogIn_btnMouseClicked

    private void LogIn_btnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogIn_btnMouseMoved
        // TODO add your handling code here:
        LogIn_btn.setBackground(Color.GRAY);

    }//GEN-LAST:event_LogIn_btnMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogIn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JButton LogIn_btn;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel SignUp;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
